version: "3"

services:
  # Database

  mongo:
    image: mongo

  redis:
    image: redis

  # Parse

  server:
    image: parseplatform/parse-server
    ports:
      - 1337:1337
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    environment:
      PARSE_SERVER_APPLICATION_ID: appId
      PARSE_SERVER_MASTER_KEY: masterKey
      # PARSE_SERVER_URL:
      # PARSE_SERVER_MASTER_KEY_IPS
      PARSE_SERVER_APP_NAME: 'My Application'
      # PARSE_SERVER_ANALYTICS_ADAPTER:
      # PARSE_SERVER_FILES_ADAPTER='filesAdapter'
      #  PARSE_SERVER_PUSH='push'
      # PARSE_SERVER_SCHEDULED_PUSH='scheduledPush'
      # PARSE_SERVER_LOGGER_ADAPTER='loggerAdapter'
      # JSON_LOGS='jsonLogs'
      # PARSE_SERVER_LOGS_FOLDER='logsFolder'
      #VERBOSE: 1
      # PARSE_SERVER_LOG_LEVEL='logLevel'
      # SILENT='silent'
      PARSE_SERVER_DATABASE_URI: mongodb://mongo/myApp
      # PARSE_SERVER_DATABASE_OPTIONS='databaseOptions'
      # PARSE_SERVER_DATABASE_ADAPTER='databaseAdapter'
      # PARSE_SERVER_CLOUD='cloud'
      # PARSE_SERVER_COLLECTION_PREFIX='collectionPrefix'
      PARSE_SERVER_CLIENT_KEY: clientKey
      PARSE_SERVER_JAVASCRIPT_KEY: javascriptKey
      PARSE_SERVER_DOT_NET_KEY: dotNetKey
      PARSE_SERVER_REST_API_KEY: restApiKey
      PARSE_SERVER_READ_ONLY_MASTER_KEY: readOnlyMasterKey
      PARSE_SERVER_WEBHOOK_KEY: webhookKey
      PARSE_SERVER_FILE_KEY: fileKey
      # PARSE_SERVER_PRESERVE_FILE_NAME='preserveFileName'
      # PARSE_SERVER_USER_SENSITIVE_FIELDS='userSensitiveFields'
      PARSE_SERVER_ENABLE_ANON_USERS: 1
      PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION: 1
      PARSE_SERVER_AUTH_PROVIDERS: '{}'
      PARSE_SERVER_MAX_UPLOAD_SIZE: 100mb
      PARSE_SERVER_VERIFY_USER_EMAILS: 0
      PARSE_SERVER_PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL: 0
      # PARSE_SERVER_EMAIL_VERIFY_TOKEN_VALIDITY_DURATION='emailVerifyTokenValidityDuration'
      # PARSE_SERVER_ACCOUNT_LOCKOUT='accountLockout'
      # PARSE_SERVER_PASSWORD_POLICY='passwordPolicy'
      # PARSE_SERVER_CACHE_ADAPTER='cacheAdapter'
      # PARSE_SERVER_EMAIL_ADAPTER='emailAdapter'
      # PARSE_PUBLIC_SERVER_URL='publicServerURL'
      # PARSE_SERVER_CUSTOM_PAGES='customPages'
      # PARSE_SERVER_SESSION_LENGTH='sessionLength'
      # PARSE_SERVER_MAX_LIMIT='maxLimit'
      PARSE_SERVER_EXPIRE_INACTIVE_SESSIONS: 1
      # PARSE_SERVER_REVOKE_SESSION_ON_PASSWORD_RESET='revokeSessionOnPasswordReset'
      PARSE_SERVER_SCHEMA_CACHE_TTL: 5000
      PARSE_SERVER_CACHE_TTL: 5000
      PARSE_SERVER_CACHE_MAX_SIZE: 10000
      # PARSE_SERVER_ENABLE_SINGLE_SCHEMA_CACHE='enableSingleSchemaCache'
      # PARSE_SERVER_ENABLE_EXPRESS_ERROR_HANDLER='enableExpressErrorHandler'
      PARSE_SERVER_OBJECT_ID_SIZE: 10
      PORT: 1337
      PARSE_SERVER_HOST: '0.0.0.0'
      PARSE_SERVER_MOUNT_PATH: /parse
      # PARSE_SERVER_CLUSTER='cluster'
      # PARSE_SERVER_MIDDLEWARE='middleware'
      PARSE_SERVER_START_LIVE_QUERY_SERVER: 1
      PARSE_SERVER_LIVE_QUERY: |-
        {
          "classNames": ["Message"],
          "redisURL": "redis://redis"
        }
      PARSE_SERVER_LIVE_QUERY_SERVER_OPTIONS: |-
        {
          "redisURL": "redis://redis"
        }

  dashboard:
    image: parseplatform/parse-dashboard
    ports:
      - 4040:4040
    depends_on:
      - server
    environment:
      HOST: '0.0.0.0'
      PORT: 4040
      MOUNT_PATH: '/'
      # PARSE_DASHBOARD_TRUST_PROXY: 1
      PARSE_DASHBOARD_SERVER_URL: 'http://localhost:1337/parse'
      PARSE_DASHBOARD_MASTER_KEY: masterKey
      PARSE_DASHBOARD_APP_ID: appId
      PARSE_DASHBOARD_APP_NAME: 'Default'
      PARSE_DASHBOARD_USER_ID: 'admin'
      PARSE_DASHBOARD_USER_PASSWORD: 'admin'
      # PARSE_DASHBOARD_SSL_KEY: "sslKey"
      # PARSE_DASHBOARD_SSL_CERT: "sslCert"
      # PARSE_DASHBOARD_CONFIG: undefined // Only for reference, it must not exist
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
